// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.3
// source: image-processing-service.proto

package service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PyrMeanShiftFilteringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In string `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
}

func (x *PyrMeanShiftFilteringRequest) Reset() {
	*x = PyrMeanShiftFilteringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_processing_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PyrMeanShiftFilteringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PyrMeanShiftFilteringRequest) ProtoMessage() {}

func (x *PyrMeanShiftFilteringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_processing_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PyrMeanShiftFilteringRequest.ProtoReflect.Descriptor instead.
func (*PyrMeanShiftFilteringRequest) Descriptor() ([]byte, []int) {
	return file_image_processing_service_proto_rawDescGZIP(), []int{0}
}

func (x *PyrMeanShiftFilteringRequest) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

type PyrMeanShiftFilteringReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PyrMeanShiftFilteringReply) Reset() {
	*x = PyrMeanShiftFilteringReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_processing_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PyrMeanShiftFilteringReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PyrMeanShiftFilteringReply) ProtoMessage() {}

func (x *PyrMeanShiftFilteringReply) ProtoReflect() protoreflect.Message {
	mi := &file_image_processing_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PyrMeanShiftFilteringReply.ProtoReflect.Descriptor instead.
func (*PyrMeanShiftFilteringReply) Descriptor() ([]byte, []int) {
	return file_image_processing_service_proto_rawDescGZIP(), []int{1}
}

func (x *PyrMeanShiftFilteringReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_image_processing_service_proto protoreflect.FileDescriptor

var file_image_processing_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2e, 0x0a, 0x1c, 0x50, 0x79, 0x72,
	0x4d, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x69, 0x66, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x22, 0x36, 0x0a, 0x1a, 0x50, 0x79, 0x72,
	0x4d, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x69, 0x66, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x7f, 0x0a, 0x16, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x15, 0x50,
	0x79, 0x72, 0x4d, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x69, 0x66, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50,
	0x79, 0x72, 0x4d, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x69, 0x66, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x79, 0x72, 0x4d, 0x65, 0x61, 0x6e, 0x53, 0x68, 0x69,
	0x66, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_image_processing_service_proto_rawDescOnce sync.Once
	file_image_processing_service_proto_rawDescData = file_image_processing_service_proto_rawDesc
)

func file_image_processing_service_proto_rawDescGZIP() []byte {
	file_image_processing_service_proto_rawDescOnce.Do(func() {
		file_image_processing_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_processing_service_proto_rawDescData)
	})
	return file_image_processing_service_proto_rawDescData
}

var file_image_processing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_processing_service_proto_goTypes = []interface{}{
	(*PyrMeanShiftFilteringRequest)(nil), // 0: service.PyrMeanShiftFilteringRequest
	(*PyrMeanShiftFilteringReply)(nil),   // 1: service.PyrMeanShiftFilteringReply
}
var file_image_processing_service_proto_depIdxs = []int32{
	0, // 0: service.ImageProcessingService.PyrMeanShiftFiltering:input_type -> service.PyrMeanShiftFilteringRequest
	1, // 1: service.ImageProcessingService.PyrMeanShiftFiltering:output_type -> service.PyrMeanShiftFilteringReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_processing_service_proto_init() }
func file_image_processing_service_proto_init() {
	if File_image_processing_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_processing_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PyrMeanShiftFilteringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_processing_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PyrMeanShiftFilteringReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_processing_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_processing_service_proto_goTypes,
		DependencyIndexes: file_image_processing_service_proto_depIdxs,
		MessageInfos:      file_image_processing_service_proto_msgTypes,
	}.Build()
	File_image_processing_service_proto = out.File
	file_image_processing_service_proto_rawDesc = nil
	file_image_processing_service_proto_goTypes = nil
	file_image_processing_service_proto_depIdxs = nil
}
