// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: proto_files/image_processing_domain.proto

package service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PyrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string  `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	Sp          float32 `protobuf:"fixed32,2,opt,name=sp,proto3" json:"sp,omitempty"`
	Sr          float32 `protobuf:"fixed32,3,opt,name=sr,proto3" json:"sr,omitempty"`
	MaxLevel    int32   `protobuf:"varint,4,opt,name=maxLevel,proto3" json:"maxLevel,omitempty"`
}

func (x *PyrRequest) Reset() {
	*x = PyrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PyrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PyrRequest) ProtoMessage() {}

func (x *PyrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PyrRequest.ProtoReflect.Descriptor instead.
func (*PyrRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{0}
}

func (x *PyrRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *PyrRequest) GetSp() float32 {
	if x != nil {
		return x.Sp
	}
	return 0
}

func (x *PyrRequest) GetSr() float32 {
	if x != nil {
		return x.Sr
	}
	return 0
}

func (x *PyrRequest) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

type ContoursRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string  `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	T1          float32 `protobuf:"fixed32,2,opt,name=t1,proto3" json:"t1,omitempty"`
	T2          float32 `protobuf:"fixed32,3,opt,name=t2,proto3" json:"t2,omitempty"`
}

func (x *ContoursRequest) Reset() {
	*x = ContoursRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContoursRequest) ProtoMessage() {}

func (x *ContoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContoursRequest.ProtoReflect.Descriptor instead.
func (*ContoursRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{1}
}

func (x *ContoursRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *ContoursRequest) GetT1() float32 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *ContoursRequest) GetT2() float32 {
	if x != nil {
		return x.T2
	}
	return 0
}

type HoughLinesWithPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture   string  `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	Rho           float32 `protobuf:"fixed32,2,opt,name=rho,proto3" json:"rho,omitempty"`
	Theta         float32 `protobuf:"fixed32,3,opt,name=theta,proto3" json:"theta,omitempty"`
	Threshold     int32   `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	MinLineLength float32 `protobuf:"fixed32,5,opt,name=minLineLength,proto3" json:"minLineLength,omitempty"`
	MaxLineGap    float32 `protobuf:"fixed32,6,opt,name=maxLineGap,proto3" json:"maxLineGap,omitempty"`
}

func (x *HoughLinesWithPRequest) Reset() {
	*x = HoughLinesWithPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoughLinesWithPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoughLinesWithPRequest) ProtoMessage() {}

func (x *HoughLinesWithPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoughLinesWithPRequest.ProtoReflect.Descriptor instead.
func (*HoughLinesWithPRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{2}
}

func (x *HoughLinesWithPRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *HoughLinesWithPRequest) GetRho() float32 {
	if x != nil {
		return x.Rho
	}
	return 0
}

func (x *HoughLinesWithPRequest) GetTheta() float32 {
	if x != nil {
		return x.Theta
	}
	return 0
}

func (x *HoughLinesWithPRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *HoughLinesWithPRequest) GetMinLineLength() float32 {
	if x != nil {
		return x.MinLineLength
	}
	return 0
}

func (x *HoughLinesWithPRequest) GetMaxLineGap() float32 {
	if x != nil {
		return x.MaxLineGap
	}
	return 0
}

type HoughCirclesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string  `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	Dp          float32 `protobuf:"fixed32,2,opt,name=dp,proto3" json:"dp,omitempty"`
	MinDist     float32 `protobuf:"fixed32,3,opt,name=minDist,proto3" json:"minDist,omitempty"`
	P1          float32 `protobuf:"fixed32,4,opt,name=p1,proto3" json:"p1,omitempty"`
	P2          float32 `protobuf:"fixed32,5,opt,name=p2,proto3" json:"p2,omitempty"`
	MinR        int32   `protobuf:"varint,6,opt,name=minR,proto3" json:"minR,omitempty"`
	MaxR        int32   `protobuf:"varint,7,opt,name=maxR,proto3" json:"maxR,omitempty"`
}

func (x *HoughCirclesRequest) Reset() {
	*x = HoughCirclesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoughCirclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoughCirclesRequest) ProtoMessage() {}

func (x *HoughCirclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoughCirclesRequest.ProtoReflect.Descriptor instead.
func (*HoughCirclesRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{3}
}

func (x *HoughCirclesRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *HoughCirclesRequest) GetDp() float32 {
	if x != nil {
		return x.Dp
	}
	return 0
}

func (x *HoughCirclesRequest) GetMinDist() float32 {
	if x != nil {
		return x.MinDist
	}
	return 0
}

func (x *HoughCirclesRequest) GetP1() float32 {
	if x != nil {
		return x.P1
	}
	return 0
}

func (x *HoughCirclesRequest) GetP2() float32 {
	if x != nil {
		return x.P2
	}
	return 0
}

func (x *HoughCirclesRequest) GetMinR() int32 {
	if x != nil {
		return x.MinR
	}
	return 0
}

func (x *HoughCirclesRequest) GetMaxR() int32 {
	if x != nil {
		return x.MaxR
	}
	return 0
}

type ThresholdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string  `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	Thresh      float32 `protobuf:"fixed32,2,opt,name=thresh,proto3" json:"thresh,omitempty"`
	Maxvalue    float32 `protobuf:"fixed32,3,opt,name=maxvalue,proto3" json:"maxvalue,omitempty"`
}

func (x *ThresholdRequest) Reset() {
	*x = ThresholdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdRequest) ProtoMessage() {}

func (x *ThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdRequest.ProtoReflect.Descriptor instead.
func (*ThresholdRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{4}
}

func (x *ThresholdRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *ThresholdRequest) GetThresh() float32 {
	if x != nil {
		return x.Thresh
	}
	return 0
}

func (x *ThresholdRequest) GetMaxvalue() float32 {
	if x != nil {
		return x.Maxvalue
	}
	return 0
}

type WatershedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	NErode      int32  `protobuf:"varint,2,opt,name=nErode,proto3" json:"nErode,omitempty"`
	NDilate     int32  `protobuf:"varint,3,opt,name=nDilate,proto3" json:"nDilate,omitempty"`
}

func (x *WatershedRequest) Reset() {
	*x = WatershedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatershedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatershedRequest) ProtoMessage() {}

func (x *WatershedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatershedRequest.ProtoReflect.Descriptor instead.
func (*WatershedRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{5}
}

func (x *WatershedRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *WatershedRequest) GetNErode() int32 {
	if x != nil {
		return x.NErode
	}
	return 0
}

func (x *WatershedRequest) GetNDilate() int32 {
	if x != nil {
		return x.NDilate
	}
	return 0
}

type CloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	KernelSize  int32  `protobuf:"varint,2,opt,name=kernelSize,proto3" json:"kernelSize,omitempty"`
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{6}
}

func (x *CloseRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *CloseRequest) GetKernelSize() int32 {
	if x != nil {
		return x.KernelSize
	}
	return 0
}

type OpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	KernelSize  int32  `protobuf:"varint,2,opt,name=kernelSize,proto3" json:"kernelSize,omitempty"`
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{7}
}

func (x *OpenRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *OpenRequest) GetKernelSize() int32 {
	if x != nil {
		return x.KernelSize
	}
	return 0
}

type DefaultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutPicture string `protobuf:"bytes,1,opt,name=OutPicture,proto3" json:"OutPicture,omitempty"`
}

func (x *DefaultReply) Reset() {
	*x = DefaultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultReply) ProtoMessage() {}

func (x *DefaultReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultReply.ProtoReflect.Descriptor instead.
func (*DefaultReply) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{8}
}

func (x *DefaultReply) GetOutPicture() string {
	if x != nil {
		return x.OutPicture
	}
	return ""
}

type SeparationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MainColorS  string `protobuf:"bytes,1,opt,name=mainColorS,proto3" json:"mainColorS,omitempty"`
	ColorFabric string `protobuf:"bytes,2,opt,name=colorFabric,proto3" json:"colorFabric,omitempty"`
	SpaceType   int32  `protobuf:"varint,3,opt,name=spaceType,proto3" json:"spaceType,omitempty"`
}

func (x *SeparationRequest) Reset() {
	*x = SeparationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeparationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeparationRequest) ProtoMessage() {}

func (x *SeparationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeparationRequest.ProtoReflect.Descriptor instead.
func (*SeparationRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{9}
}

func (x *SeparationRequest) GetMainColorS() string {
	if x != nil {
		return x.MainColorS
	}
	return ""
}

func (x *SeparationRequest) GetColorFabric() string {
	if x != nil {
		return x.ColorFabric
	}
	return ""
}

func (x *SeparationRequest) GetSpaceType() int32 {
	if x != nil {
		return x.SpaceType
	}
	return 0
}

type SeparationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlendStructures []*SeparationReply_BlendStructure `protobuf:"bytes,1,rep,name=blendStructures,proto3" json:"blendStructures,omitempty"`
}

func (x *SeparationReply) Reset() {
	*x = SeparationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeparationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeparationReply) ProtoMessage() {}

func (x *SeparationReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeparationReply.ProtoReflect.Descriptor instead.
func (*SeparationReply) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{10}
}

func (x *SeparationReply) GetBlendStructures() []*SeparationReply_BlendStructure {
	if x != nil {
		return x.BlendStructures
	}
	return nil
}

type PictureInDominatedColorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InPicture        string `protobuf:"bytes,1,opt,name=InPicture,proto3" json:"InPicture,omitempty"`
	OutPicture       string `protobuf:"bytes,2,opt,name=OutPicture,proto3" json:"OutPicture,omitempty"`
	NumberOfClusters int32  `protobuf:"varint,3,opt,name=NumberOfClusters,proto3" json:"NumberOfClusters,omitempty"`
}

func (x *PictureInDominatedColorsRequest) Reset() {
	*x = PictureInDominatedColorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureInDominatedColorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureInDominatedColorsRequest) ProtoMessage() {}

func (x *PictureInDominatedColorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureInDominatedColorsRequest.ProtoReflect.Descriptor instead.
func (*PictureInDominatedColorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{11}
}

func (x *PictureInDominatedColorsRequest) GetInPicture() string {
	if x != nil {
		return x.InPicture
	}
	return ""
}

func (x *PictureInDominatedColorsRequest) GetOutPicture() string {
	if x != nil {
		return x.OutPicture
	}
	return ""
}

func (x *PictureInDominatedColorsRequest) GetNumberOfClusters() int32 {
	if x != nil {
		return x.NumberOfClusters
	}
	return 0
}

type SeparationReply_BlendStructure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C1Hex     string `protobuf:"bytes,1,opt,name=C1Hex,proto3" json:"C1Hex,omitempty"`
	C2Hex     string `protobuf:"bytes,2,opt,name=C2Hex,proto3" json:"C2Hex,omitempty"`
	C3Hex     string `protobuf:"bytes,3,opt,name=C3Hex,proto3" json:"C3Hex,omitempty"`
	C2Portion string `protobuf:"bytes,4,opt,name=C2Portion,proto3" json:"C2Portion,omitempty"`
	C3Portion string `protobuf:"bytes,5,opt,name=C3Portion,proto3" json:"C3Portion,omitempty"`
	ResultHex string `protobuf:"bytes,6,opt,name=ResultHex,proto3" json:"ResultHex,omitempty"`
}

func (x *SeparationReply_BlendStructure) Reset() {
	*x = SeparationReply_BlendStructure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_image_processing_domain_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeparationReply_BlendStructure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeparationReply_BlendStructure) ProtoMessage() {}

func (x *SeparationReply_BlendStructure) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_image_processing_domain_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeparationReply_BlendStructure.ProtoReflect.Descriptor instead.
func (*SeparationReply_BlendStructure) Descriptor() ([]byte, []int) {
	return file_proto_files_image_processing_domain_proto_rawDescGZIP(), []int{10, 0}
}

func (x *SeparationReply_BlendStructure) GetC1Hex() string {
	if x != nil {
		return x.C1Hex
	}
	return ""
}

func (x *SeparationReply_BlendStructure) GetC2Hex() string {
	if x != nil {
		return x.C2Hex
	}
	return ""
}

func (x *SeparationReply_BlendStructure) GetC3Hex() string {
	if x != nil {
		return x.C3Hex
	}
	return ""
}

func (x *SeparationReply_BlendStructure) GetC2Portion() string {
	if x != nil {
		return x.C2Portion
	}
	return ""
}

func (x *SeparationReply_BlendStructure) GetC3Portion() string {
	if x != nil {
		return x.C3Portion
	}
	return ""
}

func (x *SeparationReply_BlendStructure) GetResultHex() string {
	if x != nil {
		return x.ResultHex
	}
	return ""
}

var File_proto_files_image_processing_domain_proto protoreflect.FileDescriptor

var file_proto_files_image_processing_domain_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x22, 0x6a, 0x0a, 0x0a, 0x50, 0x79, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x73, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x73, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x53, 0x0a, 0x0f,
	0x43, 0x6f, 0x6e, 0x74, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x74,
	0x31, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x74,
	0x32, 0x22, 0xc6, 0x01, 0x0a, 0x16, 0x48, 0x6f, 0x75, 0x67, 0x68, 0x4c, 0x69, 0x6e, 0x65, 0x73,
	0x57, 0x69, 0x74, 0x68, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x68, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x68, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x74, 0x68, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x6e, 0x65, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x6d, 0x69, 0x6e,
	0x4c, 0x69, 0x6e, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61,
	0x78, 0x4c, 0x69, 0x6e, 0x65, 0x47, 0x61, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x6d, 0x61, 0x78, 0x4c, 0x69, 0x6e, 0x65, 0x47, 0x61, 0x70, 0x22, 0xa9, 0x01, 0x0a, 0x13, 0x48,
	0x6f, 0x75, 0x67, 0x68, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x02, 0x64, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x70, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70, 0x31, 0x12, 0x0e,
	0x0a, 0x02, 0x70, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70, 0x32, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x69, 0x6e, 0x52, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x69,
	0x6e, 0x52, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x78, 0x52, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6d, 0x61, 0x78, 0x52, 0x22, 0x68, 0x0a, 0x10, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61,
	0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x74, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x66, 0x0a, 0x10, 0x57, 0x61, 0x74, 0x65, 0x72, 0x73, 0x68, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x45, 0x72, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x45, 0x72, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x44, 0x69, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6e, 0x44, 0x69, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x50, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6b, 0x65,
	0x72, 0x6e, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x4f, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74,
	0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6b,
	0x65, 0x72, 0x6e, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x2e, 0x0a, 0x0c, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x4f,
	0x75, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x4f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x73, 0x0a, 0x11, 0x53,
	0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x53, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x53,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x46, 0x61, 0x62, 0x72,
	0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x8f, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0f, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x0f, 0x62, 0x6c, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x1a, 0xac, 0x01, 0x0a, 0x0e, 0x42, 0x6c, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x31, 0x48, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x31, 0x48, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x32, 0x48, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x32, 0x48,
	0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x33, 0x48, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x43, 0x33, 0x48, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x32, 0x50, 0x6f,
	0x72, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x32, 0x50,
	0x6f, 0x72, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x33, 0x50, 0x6f, 0x72, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x33, 0x50, 0x6f, 0x72,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x65,
	0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48,
	0x65, 0x78, 0x22, 0x8b, 0x01, 0x0a, 0x1f, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x6e,
	0x44, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x75, 0x74, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x73,
	0x42, 0x37, 0x5a, 0x35, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_files_image_processing_domain_proto_rawDescOnce sync.Once
	file_proto_files_image_processing_domain_proto_rawDescData = file_proto_files_image_processing_domain_proto_rawDesc
)

func file_proto_files_image_processing_domain_proto_rawDescGZIP() []byte {
	file_proto_files_image_processing_domain_proto_rawDescOnce.Do(func() {
		file_proto_files_image_processing_domain_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_image_processing_domain_proto_rawDescData)
	})
	return file_proto_files_image_processing_domain_proto_rawDescData
}

var file_proto_files_image_processing_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_files_image_processing_domain_proto_goTypes = []interface{}{
	(*PyrRequest)(nil),                      // 0: api.PyrRequest
	(*ContoursRequest)(nil),                 // 1: api.ContoursRequest
	(*HoughLinesWithPRequest)(nil),          // 2: api.HoughLinesWithPRequest
	(*HoughCirclesRequest)(nil),             // 3: api.HoughCirclesRequest
	(*ThresholdRequest)(nil),                // 4: api.ThresholdRequest
	(*WatershedRequest)(nil),                // 5: api.WatershedRequest
	(*CloseRequest)(nil),                    // 6: api.CloseRequest
	(*OpenRequest)(nil),                     // 7: api.OpenRequest
	(*DefaultReply)(nil),                    // 8: api.DefaultReply
	(*SeparationRequest)(nil),               // 9: api.SeparationRequest
	(*SeparationReply)(nil),                 // 10: api.SeparationReply
	(*PictureInDominatedColorsRequest)(nil), // 11: api.PictureInDominatedColorsRequest
	(*SeparationReply_BlendStructure)(nil),  // 12: api.SeparationReply.BlendStructure
}
var file_proto_files_image_processing_domain_proto_depIdxs = []int32{
	12, // 0: api.SeparationReply.blendStructures:type_name -> api.SeparationReply.BlendStructure
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_files_image_processing_domain_proto_init() }
func file_proto_files_image_processing_domain_proto_init() {
	if File_proto_files_image_processing_domain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_image_processing_domain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PyrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContoursRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoughLinesWithPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoughCirclesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThresholdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatershedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeparationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeparationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureInDominatedColorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_image_processing_domain_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeparationReply_BlendStructure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_image_processing_domain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_files_image_processing_domain_proto_goTypes,
		DependencyIndexes: file_proto_files_image_processing_domain_proto_depIdxs,
		MessageInfos:      file_proto_files_image_processing_domain_proto_msgTypes,
	}.Build()
	File_proto_files_image_processing_domain_proto = out.File
	file_proto_files_image_processing_domain_proto_rawDesc = nil
	file_proto_files_image_processing_domain_proto_goTypes = nil
	file_proto_files_image_processing_domain_proto_depIdxs = nil
}
