// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: image_processing_domain.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PyrRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathPicture string  `protobuf:"bytes,1,opt,name=pathPicture,proto3" json:"pathPicture,omitempty"`
	Sp          float32 `protobuf:"fixed32,2,opt,name=sp,proto3" json:"sp,omitempty"`
	Sr          float32 `protobuf:"fixed32,3,opt,name=sr,proto3" json:"sr,omitempty"`
	MaxLevel    int32   `protobuf:"varint,4,opt,name=maxLevel,proto3" json:"maxLevel,omitempty"`
}

func (x *PyrRequest) Reset() {
	*x = PyrRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_processing_domain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PyrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PyrRequest) ProtoMessage() {}

func (x *PyrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_processing_domain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PyrRequest.ProtoReflect.Descriptor instead.
func (*PyrRequest) Descriptor() ([]byte, []int) {
	return file_image_processing_domain_proto_rawDescGZIP(), []int{0}
}

func (x *PyrRequest) GetPathPicture() string {
	if x != nil {
		return x.PathPicture
	}
	return ""
}

func (x *PyrRequest) GetSp() float32 {
	if x != nil {
		return x.Sp
	}
	return 0
}

func (x *PyrRequest) GetSr() float32 {
	if x != nil {
		return x.Sr
	}
	return 0
}

func (x *PyrRequest) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

type DefaultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutPicture string `protobuf:"bytes,1,opt,name=OutPicture,proto3" json:"OutPicture,omitempty"`
}

func (x *DefaultReply) Reset() {
	*x = DefaultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_processing_domain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultReply) ProtoMessage() {}

func (x *DefaultReply) ProtoReflect() protoreflect.Message {
	mi := &file_image_processing_domain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultReply.ProtoReflect.Descriptor instead.
func (*DefaultReply) Descriptor() ([]byte, []int) {
	return file_image_processing_domain_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultReply) GetOutPicture() string {
	if x != nil {
		return x.OutPicture
	}
	return ""
}

var File_image_processing_domain_proto protoreflect.FileDescriptor

var file_image_processing_domain_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x69,
	0x6e, 0x67, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x6a, 0x0a, 0x0a, 0x50, 0x79, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x74, 0x68, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x02, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x02, 0x73, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x2e, 0x0a, 0x0c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x75, 0x74, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x42, 0x14, 0x5a, 0x12, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_processing_domain_proto_rawDescOnce sync.Once
	file_image_processing_domain_proto_rawDescData = file_image_processing_domain_proto_rawDesc
)

func file_image_processing_domain_proto_rawDescGZIP() []byte {
	file_image_processing_domain_proto_rawDescOnce.Do(func() {
		file_image_processing_domain_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_processing_domain_proto_rawDescData)
	})
	return file_image_processing_domain_proto_rawDescData
}

var file_image_processing_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_processing_domain_proto_goTypes = []interface{}{
	(*PyrRequest)(nil),   // 0: api.PyrRequest
	(*DefaultReply)(nil), // 1: api.DefaultReply
}
var file_image_processing_domain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_processing_domain_proto_init() }
func file_image_processing_domain_proto_init() {
	if File_image_processing_domain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_processing_domain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PyrRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_processing_domain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_processing_domain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_processing_domain_proto_goTypes,
		DependencyIndexes: file_image_processing_domain_proto_depIdxs,
		MessageInfos:      file_image_processing_domain_proto_msgTypes,
	}.Build()
	File_image_processing_domain_proto = out.File
	file_image_processing_domain_proto_rawDesc = nil
	file_image_processing_domain_proto_goTypes = nil
	file_image_processing_domain_proto_depIdxs = nil
}
