// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"bytes"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RenderHandlerFunc turns a function with the right signature into a render handler
type RenderHandlerFunc func(RenderParams) RenderResponder

// Handle executing the request and returning a response
func (fn RenderHandlerFunc) Handle(params RenderParams) RenderResponder {
	return fn(params)
}

// RenderHandler interface for that can handle valid render params
type RenderHandler interface {
	Handle(RenderParams) RenderResponder
}

// NewRender creates a new http.Handler for the render operation
func NewRender(ctx *middleware.Context, handler RenderHandler) *Render {
	return &Render{Context: ctx, Handler: handler}
}

/*Render swagger:route GET /render render

render

*/
type Render struct {
	Context *middleware.Context
	Handler RenderHandler
}

func (o *Render) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRenderParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// RenderOKBody render o k body
//
// swagger:model RenderOKBody
type RenderOKBody struct {

	// result
	// Required: true
	Result interface{} `json:"result"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *RenderOKBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// result
		// Required: true
		Result interface{} `json:"result"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Result = props.Result
	return nil
}

// Validate validates this render o k body
func (o *RenderOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RenderOKBody) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("renderOK"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RenderOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RenderOKBody) UnmarshalBinary(b []byte) error {
	var res RenderOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
