// Code generated by go-swagger; DO NOT EDIT.

package op

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"bytes"
	"encoding/json"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScobelHandlerFunc turns a function with the right signature into a scobel handler
type ScobelHandlerFunc func(ScobelParams) ScobelResponder

// Handle executing the request and returning a response
func (fn ScobelHandlerFunc) Handle(params ScobelParams) ScobelResponder {
	return fn(params)
}

// ScobelHandler interface for that can handle valid scobel params
type ScobelHandler interface {
	Handle(ScobelParams) ScobelResponder
}

// NewScobel creates a new http.Handler for the scobel operation
func NewScobel(ctx *middleware.Context, handler ScobelHandler) *Scobel {
	return &Scobel{Context: ctx, Handler: handler}
}

/*Scobel swagger:route GET /scobel scobel

scobel

*/
type Scobel struct {
	Context *middleware.Context
	Handler ScobelHandler
}

func (o *Scobel) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewScobelParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ScobelOKBody scobel o k body
//
// swagger:model ScobelOKBody
type ScobelOKBody struct {

	// result
	// Required: true
	Result interface{} `json:"result"`
}

// UnmarshalJSON unmarshals this object while disallowing additional properties from JSON
func (o *ScobelOKBody) UnmarshalJSON(data []byte) error {
	var props struct {

		// result
		// Required: true
		Result interface{} `json:"result"`
	}

	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&props); err != nil {
		return err
	}

	o.Result = props.Result
	return nil
}

// Validate validates this scobel o k body
func (o *ScobelOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ScobelOKBody) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("scobelOK"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ScobelOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ScobelOKBody) UnmarshalBinary(b []byte) error {
	var res ScobelOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
